create extension if not exists pgcrypto;

create table if not exists public.gemini_checker_users (
  telegram_user_id bigint primary key,
  username text,
  first_name text,
  last_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gemini_checker_checks (
  id uuid primary key default gen_random_uuid(),
  telegram_user_id bigint references public.gemini_checker_users(telegram_user_id) on delete set null,
  input_type text not null default 'text' check (input_type in ('text', 'txt')),
  total integer not null default 0,
  valid integer not null default 0,
  used integer not null default 0,
  expired integer not null default 0,
  invalid integer not null default 0,
  error integer not null default 0,
  duration_ms integer,
  created_at timestamptz not null default now()
);

create table if not exists public.gemini_checker_items (
  id bigint generated by default as identity primary key,
  check_id uuid not null references public.gemini_checker_checks(id) on delete cascade,
  position integer not null,
  link_hash text not null,
  raw_link text,
  status text not null check (status in ('valid', 'used', 'expired', 'invalid', 'error')),
  reason text,
  http_status integer,
  final_url text,
  duration_ms integer,
  engine text,
  confidence text,
  evidence jsonb,
  created_at timestamptz not null default now(),
  unique (check_id, position)
);

create index if not exists gemini_checker_checks_user_created_idx
  on public.gemini_checker_checks (telegram_user_id, created_at desc);
create index if not exists gemini_checker_items_check_idx
  on public.gemini_checker_items (check_id);
create index if not exists gemini_checker_items_hash_idx
  on public.gemini_checker_items (link_hash);

alter table public.gemini_checker_users enable row level security;
alter table public.gemini_checker_checks enable row level security;
alter table public.gemini_checker_items enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on table public.gemini_checker_users to service_role;
grant select, insert, update, delete on table public.gemini_checker_checks to service_role;
grant select, insert, update, delete on table public.gemini_checker_items to service_role;
grant usage, select on sequence public.gemini_checker_items_id_seq to service_role;

-- Aman dijalankan juga pada database versi lama.
alter table public.gemini_checker_items add column if not exists engine text;
alter table public.gemini_checker_items add column if not exists confidence text;
alter table public.gemini_checker_items add column if not exists evidence jsonb;

NOTIFY pgrst, 'reload schema';
